# SFT Training: google/gemma-3-4b-it

## 1. Установка зависимостей, импорты, настройка

In [1]:
%%capture
!pip install -q transformers==4.47.1 trl==0.12.2 accelerate==1.2.1 bitsandbytes==0.45.0 peft==0.14.0
!pip install -q torch torchvision --index-url https://download.pytorch.org/whl/cu121

In [2]:
!pip install trl

Collecting trl
  Downloading trl-1.6.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: accelerate>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from trl) (1.14.0)
Collecting datasets>=4.7.0 (from trl)
  Downloading datasets-5.0.0-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from trl) (3.1.6)
Requirement already satisfied: packaging>20.0 in /usr/local/lib/python3.12/dist-packages (from trl) (26.2)
Requirement already satisfied: transformers>=4.56.2 in /usr/local/lib/python3.12/dist-packages (from trl) (5.12.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (2.0.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (2.11.0+cpu)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (1.19.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (0.8.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (3.29.3)
Collecting pyarrow>=21.0.0 (from datasets>=4.7.0->trl)
  Downloading pyarrow-24.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (3.7.0)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.70.16)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (2025.3.0)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (0.25.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->trl) (3.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=4.7.0->trl) (0.16.0)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (8.4.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (1.5.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (2.5.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.6.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.56.2->trl) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.56.2->trl) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.56.2->trl) (0.0.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2026.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=4.7.0->trl) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers>=4.56.2->trl) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers>=4.56.2->trl) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate>=1.4.0->trl) (1.3.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers>=4.56.2->trl) (0.1.2)
Downloading trl-1.6.0-py3-none-any.whl (825 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 825.1/825.1 kB 39.9 MB/s eta 0:00:00
Downloading datasets-5.0.0-py3-none-any.whl (555 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 555.1/555.1 kB 29.2 MB/s eta 0:00:00
Downloading pyarrow-24.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (48.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 MB 38.7 MB/s eta 0:00:00
Installing collected packages: pyarrow, datasets, trl
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
  Attempting uninstall: datasets
    Found existing installation: datasets 4.0.0
    Uninstalling datasets-4.0.0:
      Successfully uninstalled datasets-4.0.0
Successfully installed datasets-5.0.0 pyarrow-24.0.0 trl-1.6.0

In [3]:
import os, sys, json, gc, math, shutil, textwrap, warnings
from pathlib import Path
from datetime import datetime
from copy import deepcopy

import torch
import transformers
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    TrainingArguments,
    TrainerCallback,
    BitsAndBytesConfig,
)
from trl import SFTTrainer
from datasets import Dataset

warnings.filterwarnings('ignore')
print(f"PyTorch  : {torch.__version__}")
print(f"Transformers: {transformers.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

PyTorch  : 2.11.0+cpu
Transformers: 5.12.0
CUDA available: False

Мы использовали A100 для дообучения

In [4]:
MODEL_ID = "google/gemma-3-4b-it"

from google.colab import drive
drive.mount('/content/drive')

DRIVE_BASE   = Path("/content/drive/MyDrive/Colab Notebooks/gemma3_sft")
CKPT_DIR     = DRIVE_BASE / "checkpoints"
DATA_DIR     = Path("/content/drive/MyDrive/Colab Notebooks")
FINAL_DIR    = DRIVE_BASE / "final_model"

for d in [CKPT_DIR, DATA_DIR, FINAL_DIR]:
    d.mkdir(parents=True, exist_ok=True)

print("Директории созданы:")
print(f"  Чекпоинты : {CKPT_DIR}")
print(f"  Финальная : {FINAL_DIR}")

Mounted at /content/drive
Директории созданы:
  Чекпоинты : /content/drive/MyDrive/Colab Notebooks/gemma3_sft/checkpoints
  Финальная : /content/drive/MyDrive/Colab Notebooks/gemma3_sft/final_model

## 2. Загрузка и валидация данных

In [5]:
#Валидация JSON-файлов
def validate_and_load(path: Path, name: str) -> list:
    """Загружает JSON, проверяет формат, фильтрует пустые примеры."""
    assert path.exists(), f"Файл не найден: {path}"
    with open(path, encoding='utf-8') as f:
        data = json.load(f)

    assert isinstance(data, list), f"{name}: ожидался list, получен {type(data)}"

    clean, skipped = [], 0
    for idx, item in enumerate(data):
        assert isinstance(item, dict), f"{name}[{idx}]: элемент не dict"
        assert 'conversations' in item, f"{name}[{idx}]: нет поля 'conversations'"
        convs = item['conversations']
        assert isinstance(convs, list) and len(convs) >= 2, \
            f"{name}[{idx}]: 'conversations' должен быть списком ≥ 2 сообщений"

        # Проверяем роли и непустые значения
        valid = True
        for msg in convs:
            assert 'from' in msg and 'value' in msg, \
                f"{name}[{idx}]: сообщение без 'from' или 'value'"
            if not msg['value'].strip():
                valid = False  # пропускаем примеры с пустым ответом
                skipped += 1
                break

        if valid:
            clean.append(item)

    print(f"  [{name}] Загружено: {len(data)}, отфильтровано пустых: {skipped}, итого: {len(clean)}")
    return clean


raw = {
    'easy'         : validate_and_load(DATA_DIR / 'easy.json',         'easy'),
    'medium_part1' : validate_and_load(DATA_DIR / 'medium_part1.json', 'medium_part1'),
    'medium_part2' : validate_and_load(DATA_DIR / 'medium_part2.json', 'medium_part2'),
    'hard'         : validate_and_load(DATA_DIR / 'hard.json',         'hard'),
}

  [easy] Загружено: 8077, отфильтровано пустых: 0, итого: 8077
  [medium_part1] Загружено: 12154, отфильтровано пустых: 1, итого: 12153
  [medium_part2] Загружено: 12155, отфильтровано пустых: 0, итого: 12155
  [hard] Загружено: 6479, отфильтровано пустых: 0, итого: 6479

## 3. Загрузка токенизатора и модели

In [6]:
# HuggingFace токен
from huggingface_hub import login
login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [7]:
# Гиперпараметры
MODEL_MAX_LENGTH          = 1024
LEARNING_RATE             = 2e-5
WEIGHT_DECAY              = 0.0
WARMUP_RATIO              = 0.03
LR_SCHEDULER_TYPE         = "cosine"
GRADIENT_ACCUMULATION     = 16
LOGGING_STEPS             = 1
PER_DEVICE_TRAIN_BATCH    = 1
DTYPE                     = torch.bfloat16

In [19]:
print(f"Загружаем токенизатор: {MODEL_ID}")
tokenizer = AutoTokenizer.from_pretrained(
    MODEL_ID,
    model_max_length=MODEL_MAX_LENGTH,
    padding_side='right',
)

# Gemma уже имеет pad_token, но проверим
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
    print("pad_token установлен в eos_token")

print(f"Vocab size : {len(tokenizer)}")
print(f"pad_token  : {tokenizer.pad_token!r} (id={tokenizer.pad_token_id})")
print(f"eos_token  : {tokenizer.eos_token!r} (id={tokenizer.eos_token_id})")
print(f"bos_token  : {tokenizer.bos_token!r} (id={tokenizer.bos_token_id})")

Загружаем токенизатор: google/gemma-3-4b-it

config.json:   0%|          | 0.00/855 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.16M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/33.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/35.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

Vocab size : 262145
pad_token  : '<pad>' (id=0)
eos_token  : '<eos>' (id=1)
bos_token  : '<bos>' (id=2)

In [ ]:
def load_base_model(checkpoint_path: str = None) -> AutoModelForCausalLM:
    """
    Загружает модель из HuggingFace Hub
    """
    src = checkpoint_path if checkpoint_path else MODEL_ID
    print(f"Загружаем модель из: {src}")

    model = AutoModelForCausalLM.from_pretrained(
        src,
        torch_dtype=DTYPE,
        device_map="auto",
        attn_implementation="eager",
    )
    model.config.use_cache = False
    model.enable_input_require_grads()  # нужно для gradient checkpointing + SFT
    print(f"Параметров: {sum(p.numel() for p in model.parameters()) / 1e9:.2f}B")
    return model


# Загружаем начальную модель
model = load_base_model()
print("Модель загружена")

Загружаем модель из: google/gemma-3-4b-it

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json:   0%|          | 0.00/90.6k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/883 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/215 [00:00<?, ?B/s]

Параметров: 4.30B
Модель загружена

## 4. Вспомогательные функции

In [ ]:
#Конвертация данных в chat-формат
def conversations_to_text(sample: dict) -> dict:
    """
    Конвертирует элемент датасета в строку через apply_chat_template.
    Формат: [{role: user, content: ...}, {role: assistant, content: ...}, ...]
    """
    messages = []
    role_map = {'human': 'user', 'gpt': 'assistant', 'system': 'system'}
    for msg in sample['conversations']:
        role = role_map.get(msg['from'], msg['from'])
        messages.append({'role': role, 'content': msg['value']})

    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=False,
    )
    return {'text': text}


def make_dataset(data: list) -> Dataset:
    """Создаёт HF Dataset из списка conversation-примеров."""
    dataset = Dataset.from_list(data)
    dataset = dataset.map(conversations_to_text, num_proc=4, desc='Форматирование')
    return dataset


# Проверка форматирования
sample_text = conversations_to_text(raw['easy'][0])['text']
print("Пример форматирования:")
print(sample_text[:500])
print(f"\nДлина: {len(tokenizer(sample_text)['input_ids'])} токенов")

Пример форматирования:
<bos><start_of_turn>user
Верно ли, что биология — это наука о живых организмах и их взаимодействии с окружающей средой?<end_of_turn>
<start_of_turn>model
верно<end_of_turn>


Длина: 38 токенов

In [11]:
#Sanity check: генерация текста
#Мы включили этот этап, потому что при предыдущей попытке дообучения у нас модель где-то сломалась
#В итоге она генерировала только паддинг, поэтому теперь мы будем проверять это сразу
#Если модель где-то сломается, то мы начнем с последнего чекпоинта
SANITY_PROMPTS = [
    "Что такое фотосинтез?",
    "Назовите три органоида клетки и их функции.",
    "Почему вода является универсальным растворителем?",
]

@torch.inference_mode()
def run_sanity_check(model, tokenizer, epoch_label: str, max_new_tokens: int = 300):
    """
    Проверяет, что модель генерирует осмысленный текст после эпохи.
    Детектирует зависание на pad-токенах.
    Возвращает True если модель в норме.
    """
    print(f"\n{'='*60}")
    print(f"SANITY CHECK после {epoch_label}")
    print(f"{'='*60}")

    model.eval()
    model.config.use_cache = True
    ok = True

    for prompt in SANITY_PROMPTS:
        messages = [{'role': 'user', 'content': prompt}]
        input_text = tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )
        inputs = tokenizer(input_text, return_tensors='pt').to(model.device)
        input_len = inputs['input_ids'].shape[1]

        try:
            output = model.generate(
                **inputs,
                max_new_tokens=max_new_tokens,
                do_sample=False,
                temperature=None,
                top_p=None,
                pad_token_id=tokenizer.pad_token_id,
                eos_token_id=tokenizer.eos_token_id,
            )
        except Exception as e:
            print(f"❌ Ошибка генерации: {e}")
            ok = False
            continue

        generated_ids = output[0][input_len:]
        generated_text = tokenizer.decode(generated_ids, skip_special_tokens=True)

        #Диагностика паддинга
        pad_id  = tokenizer.pad_token_id
        pad_count = (generated_ids == pad_id).sum().item()
        total_gen = len(generated_ids)
        pad_ratio  = pad_count / max(total_gen, 1)

        # Считаем уникальные токены (разнообразие)
        unique_tokens = len(set(generated_ids.tolist()))

        print(f"\nPrompt : {prompt}")
        print(f"Answer : {generated_text[:300]}")
        print(f"Stats  : {total_gen} токенов, {unique_tokens} уникальных, pad доля={pad_ratio:.2%}")

        # Критерии сломанной модели
        if pad_ratio > 0.5:
            print(f"⚠️ >50% токенов pad!")
            ok = False
        if unique_tokens <= 3 and total_gen > 10:
            print(f"⚠️ Мало уникальных токенов ({unique_tokens})!")
            ok = False
        if not generated_text.strip():
            print(f"⚠️ Пустая генерация!")
            ok = False

    if ok:
        print(f"\n✅ Санити-чек пройден после {epoch_label}")
    else:
        print(f"\n❌ ПРОБЛЕМА ОБНАРУЖЕНА после {epoch_label}")

    model.train()
    model.config.use_cache = False
    return ok

In [10]:
# Callback: сбор лоссов
class LossLoggerCallback(TrainerCallback):
    """Собирает train loss по шагам для последующего анализа."""
    def __init__(self):
        self.losses = []

    def on_log(self, args, state, control, logs=None, **kwargs):
        if logs and 'loss' in logs:
            self.losses.append({
                'step'  : state.global_step,
                'loss'  : logs['loss'],
                'epoch' : state.epoch,
                'lr'    : logs.get('learning_rate', None),
            })

    def summary(self, epoch_label: str):
        if not self.losses:
            print("  Нет данных о лоссе.")
            return
        losses = [x['loss'] for x in self.losses]
        print(f"  Лосс [{epoch_label}]:")
        print(f"    Первый шаг : {losses[0]:.4f}")
        print(f"    Последний  : {losses[-1]:.4f}")
        print(f"    Минимум    : {min(losses):.4f}")
        print(f"    Максимум   : {max(losses):.4f}")
        print(f"    Среднее    : {sum(losses)/len(losses):.4f}")
        self.losses.clear()  # сбрасываем для следующей эпохи


#Сохранение чекпоинта
#Дообучение идет примерно 7 часов + после какой-то эпохи может сломаться
#Надо перестраховаться
def save_checkpoint(model, tokenizer, epoch_label: str):
    ckpt_path = CKPT_DIR / epoch_label
    ckpt_path.mkdir(parents=True, exist_ok=True)
    print(f"  Сохраняем чекпоинт: {ckpt_path}")
    model.save_pretrained(str(ckpt_path))
    tokenizer.save_pretrained(str(ckpt_path))

    meta = {
        'epoch_label': epoch_label,
        'timestamp'  : datetime.now().isoformat(),
        'model_id'   : MODEL_ID,
    }
    with open(ckpt_path / 'training_meta.json', 'w') as f:
        json.dump(meta, f, indent=2, ensure_ascii=False)
    print(f"  ✅ Чекпоинт сохранён: {ckpt_path}")
    return str(ckpt_path)

## 5. Основная функция обучения одной эпохи

In [12]:
def train_one_epoch(
    model,
    tokenizer,
    dataset: Dataset,
    epoch_label: str,
    output_dir: str,
    loss_logger: LossLoggerCallback,
    num_train_epochs: int = 1,
) -> tuple:
    """
    Обучает модель на датасете в течение num_train_epochs эпох.
    Возвращает (trainer, metrics).
    """
    model.train()
    model.config.use_cache = False

    training_args = TrainingArguments(
        output_dir                  = output_dir,
        num_train_epochs            = num_train_epochs,
        per_device_train_batch_size = PER_DEVICE_TRAIN_BATCH,
        gradient_accumulation_steps = GRADIENT_ACCUMULATION,
        learning_rate               = LEARNING_RATE,
        weight_decay                = WEIGHT_DECAY,
        warmup_ratio                = WARMUP_RATIO,
        lr_scheduler_type           = LR_SCHEDULER_TYPE,
        logging_steps               = LOGGING_STEPS,
        save_strategy               = "no",
        eval_strategy               = "no",
        bf16                        = (DTYPE == torch.bfloat16),
        fp16                        = False,
        gradient_checkpointing      = True,
        gradient_checkpointing_kwargs={"use_reentrant": False},
        dataloader_num_workers      = 2,
        remove_unused_columns       = False,
        optim                       = "adamw_torch_fused",
        report_to                   = "none",
        logging_first_step          = True,
        seed                        = 42,
    )


    trainer = SFTTrainer(
    model            = model,
    args             = training_args,
    processing_class = tokenizer,
    train_dataset    = dataset,
    )

    print(f"\n{'#'*60}")
    print(f"# Начинаем обучение: {epoch_label}")
    print(f"# Примеров: {len(dataset)}, Эпох: {num_train_epochs}")
    total_steps = math.ceil(len(dataset) / (PER_DEVICE_TRAIN_BATCH * GRADIENT_ACCUMULATION)) * num_train_epochs
    print(f"# Шагов оптимизатора (приблизительно): {total_steps}")
    print(f"{'#'*60}")

    metrics = trainer.train()
    print(f"\nОбучение завершено. Loss: {metrics.training_loss:.4f}")
    return trainer, metrics

## 6. Полный цикл обучения

Сначала отформатируем и проверим данные для дообучения.
Потом уже собственно дообучение.
После каждой эпохи:
1. Лог лоссов
2. Санити-чек
3. Чекпоинт на Диск

In [13]:
# Расписание обучения
SCHEDULE = [
    ('easy',         2),
    ('medium_part1', 1),
    ('medium_part2', 1),
    ('hard',         2),
]

print("Расписание обучения:")
total_ep = 0
for ds_name, n_ep in SCHEDULE:
    total_ep += n_ep
    print(f"  {ds_name:16s} → {n_ep} эпох(а)")
print(f"  Всего эпох: {total_ep}")

Расписание обучения:
  easy             → 2 эпох(а)
  medium_part1     → 1 эпох(а)
  medium_part2     → 1 эпох(а)
  hard             → 2 эпох(а)
  Всего эпох: 6

In [20]:
#Предварительно форматируем все датасеты
datasets_formatted = {}
for ds_name, _ in SCHEDULE:
    if ds_name not in datasets_formatted:
        print(f"  {ds_name}...")
        datasets_formatted[ds_name] = make_dataset(raw[ds_name])
        print(f"    {len(datasets_formatted[ds_name])} примеров готовы")
print("\nВсе датасеты готовы")

  easy...

Форматирование (num_proc=4):   0%|          | 0/8077 [00:00<?, ? examples/s]

    8077 примеров готовы
  medium_part1...

Форматирование (num_proc=4):   0%|          | 0/12153 [00:00<?, ? examples/s]

    12153 примеров готовы
  medium_part2...

Форматирование (num_proc=4):   0%|          | 0/12155 [00:00<?, ? examples/s]

    12155 примеров готовы
  hard...

Форматирование (num_proc=4):   0%|          | 0/6479 [00:00<?, ? examples/s]

    6479 примеров готовы

Все датасеты готовы

In [ ]:
def convert_to_chatml(example):
    role_map = {"human": "user", "gpt": "assistant"}
    messages = [
        {
            "role": role_map.get(msg["from"], msg["from"]),
            "content": msg["value"]
        }
        for msg in example["conversations"]
    ]
    return {"messages": messages}

datasets_formatted = {
    name: ds.map(convert_to_chatml, remove_columns=ds.column_names)
    for name, ds in datasets_formatted.items()
}

Map:   0%|          | 0/8077 [00:00<?, ? examples/s]

Map:   0%|          | 0/12153 [00:00<?, ? examples/s]

Map:   0%|          | 0/12155 [00:00<?, ? examples/s]

Map:   0%|          | 0/6479 [00:00<?, ? examples/s]

In [ ]:
for name, ds in datasets_formatted.items():
    print(f"{name}: {len(ds)} примеров")
    print(f"  Колонки: {ds.column_names}")
    print(f"  Первый пример: {ds[0]['messages']}")

easy: 8077 примеров
  Колонки: ['messages']
  Первый пример: [{'role': 'user', 'content': 'Верно ли, что биология — это наука о живых организмах и их взаимодействии с окружающей средой?'}, {'role': 'assistant', 'content': 'верно'}]
medium_part1: 12153 примеров
  Колонки: ['messages']
  Первый пример: [{'role': 'user', 'content': 'Сформулируйте определение биологии, используя термины «изучение» и «организмы».'}, {'role': 'assistant', 'content': 'Биология — это наука, изучающая организмы и их взаимодействие с окружающей средой.'}]
medium_part2: 12155 примеров
  Колонки: ['messages']
  Первый пример: [{'role': 'user', 'content': 'Что такое географическая среда и какие компоненты она включает?'}, {'role': 'assistant', 'content': 'Географическая среда — это совокупность природных (например, климат, рельеф, водные ресурсы) и антропогенных (например, города, дороги, сельскохозяйственные угодья) компонентов, которые окружают человека и с которыми он взаимодействует.'}]
hard: 6479 примеров
  Колонки: ['messages']
  Первый пример: [{'role': 'user', 'content': 'Как можно использовать знания о взаимодействии организмов с окружающей средой для объяснения причин сокращения численности пчёл в определённом регионе?'}, {'role': 'assistant', 'content': 'Можно проанализировать изменения в окружающей среде, такие как уничтожение цветущих растений, загрязнение, использование пестицидов или изменение климата, и оценить их влияние на жизнедеятельность и выживание пчёл, основываясь на их экологических потребностях и зависимостях.'}]

In [ ]:
def is_valid_conversation(example):
    messages = example.get("messages", [])

    # Минимум 2 сообщения
    if len(messages) < 2:
        return False

    # Первое должно быть от user
    if messages[0]["role"] != "user":
        return False

    # Роли должны чередоваться
    for i, msg in enumerate(messages):
        expected_role = "user" if i % 2 == 0 else "assistant"
        if msg["role"] != expected_role:
            return False

        # Нет пустого контента
        if not msg.get("content", "").strip():
            return False

    return True


datasets_formatted = {
    name: ds.filter(is_valid_conversation)
    for name, ds in datasets_formatted.items()
}

Filter:   0%|          | 0/8077 [00:00<?, ? examples/s]

Filter:   0%|          | 0/12153 [00:00<?, ? examples/s]

Filter:   0%|          | 0/12155 [00:00<?, ? examples/s]

Filter:   0%|          | 0/6479 [00:00<?, ? examples/s]

In [ ]:
for name, ds in datasets_formatted.items():
    total   = len(ds)
    valid   = ds.filter(is_valid_conversation)
    invalid = total - len(valid)
    print(f"{name}: всего {total}, невалидных {invalid} ({100*invalid/total:.1f}%)")

Filter:   0%|          | 0/8077 [00:00<?, ? examples/s]

easy: всего 8077, невалидных 0 (0.0%)

Filter:   0%|          | 0/12153 [00:00<?, ? examples/s]

medium_part1: всего 12153, невалидных 0 (0.0%)

Filter:   0%|          | 0/12155 [00:00<?, ? examples/s]

medium_part2: всего 12155, невалидных 0 (0.0%)

Filter:   0%|          | 0/6479 [00:00<?, ? examples/s]

hard: всего 6479, невалидных 0 (0.0%)

In [ ]:
for name, ds in datasets_formatted.items():
    print(f"{name}: {len(ds)} примеров")
    if len(ds) > 0:
        print(f"  Колонки: {ds.column_names}")
        print(f"  Первый пример: {ds[0]}")

easy: 8077 примеров
  Колонки: ['id', 'conversations', 'text']
  Первый пример: {'id': '5_класс_easy_0', 'conversations': [{'from': 'human', 'value': 'Верно ли, что биология — это наука о живых организмах и их взаимодействии с окружающей средой?'}, {'from': 'gpt', 'value': 'верно'}], 'text': '<bos><start_of_turn>user\nВерно ли, что биология — это наука о живых организмах и их взаимодействии с окружающей средой?<end_of_turn>\n<start_of_turn>model\nверно<end_of_turn>\n'}
medium_part1: 12153 примеров
  Колонки: ['id', 'conversations', 'text']
  Первый пример: {'id': '5_класс_medium_306', 'conversations': [{'from': 'human', 'value': 'Сформулируйте определение биологии, используя термины «изучение» и «организмы».'}, {'from': 'gpt', 'value': 'Биология — это наука, изучающая организмы и их взаимодействие с окружающей средой.'}], 'text': '<bos><start_of_turn>user\nСформулируйте определение биологии, используя термины «изучение» и «организмы».<end_of_turn>\n<start_of_turn>model\nБиология — это наука, изучающая организмы и их взаимодействие с окружающей средой.<end_of_turn>\n'}
medium_part2: 12155 примеров
  Колонки: ['id', 'conversations', 'text']
  Первый пример: {'id': '10_класс_medium_21830', 'conversations': [{'from': 'human', 'value': 'Что такое географическая среда и какие компоненты она включает?'}, {'from': 'gpt', 'value': 'Географическая среда — это совокупность природных (например, климат, рельеф, водные ресурсы) и антропогенных (например, города, дороги, сельскохозяйственные угодья) компонентов, которые окружают человека и с которыми он взаимодействует.'}], 'text': '<bos><start_of_turn>user\nЧто такое географическая среда и какие компоненты она включает?<end_of_turn>\n<start_of_turn>model\nГеографическая среда — это совокупность природных (например, климат, рельеф, водные ресурсы) и антропогенных (например, города, дороги, сельскохозяйственные угодья) компонентов, которые окружают человека и с которыми он взаимодействует.<end_of_turn>\n'}
hard: 6479 примеров
  Колонки: ['id', 'conversations', 'text']
  Первый пример: {'id': '5_класс_hard_1246', 'conversations': [{'from': 'human', 'value': 'Как можно использовать знания о взаимодействии организмов с окружающей средой для объяснения причин сокращения численности пчёл в определённом регионе?'}, {'from': 'gpt', 'value': 'Можно проанализировать изменения в окружающей среде, такие как уничтожение цветущих растений, загрязнение, использование пестицидов или изменение климата, и оценить их влияние на жизнедеятельность и выживание пчёл, основываясь на их экологических потребностях и зависимостях.'}], 'text': '<bos><start_of_turn>user\nКак можно использовать знания о взаимодействии организмов с окружающей средой для объяснения причин сокращения численности пчёл в определённом регионе?<end_of_turn>\n<start_of_turn>model\nМожно проанализировать изменения в окружающей среде, такие как уничтожение цветущих растений, загрязнение, использование пестицидов или изменение климата, и оценить их влияние на жизнедеятельность и выживание пчёл, основываясь на их экологических потребностях и зависимостях.<end_of_turn>\n'}

In [ ]:
# ЦИКЛ ОБУЧЕНИЯ
loss_logger   = LossLoggerCallback()
epoch_counter = 0
all_checkpoints = []
sanity_results  = {}

for ds_name, n_epochs in SCHEDULE:
    dataset = datasets_formatted[ds_name]

    for ep in range(1, n_epochs + 1):
        epoch_counter += 1
        epoch_label = f"epoch{epoch_counter:02d}_{ds_name}_ep{ep}of{n_epochs}"
        tmp_output  = f"/content/tmp_trainer_{epoch_label}"

        # Обучение
        trainer, metrics = train_one_epoch(
            model        = model,
            tokenizer    = tokenizer,
            dataset      = dataset,
            epoch_label  = epoch_label,
            output_dir   = tmp_output,
            loss_logger  = loss_logger,
            num_train_epochs = 1,
        )

        # Лог лоссов
        print(f"\nЛосс эпохи {epoch_label}:")
        loss_logger.summary(epoch_label)

        # Санити-чек
        sanity_ok = run_sanity_check(model, tokenizer, epoch_label)
        sanity_results[epoch_label] = sanity_ok

        # Чекпоинт
        ckpt_path = save_checkpoint(model, tokenizer, epoch_label)
        all_checkpoints.append((epoch_label, ckpt_path, sanity_ok))

        # Чистим временную директорию трейнера
        if Path(tmp_output).exists():
            shutil.rmtree(tmp_output, ignore_errors=True)

        # Освобождаем память
        del trainer
        gc.collect()
        torch.cuda.empty_cache()

        if not sanity_ok:
            print(f"\n Модель повреждена после {epoch_label}!")
            print(f" Последний рабочий чекпоинт: {all_checkpoints[-2][1] if len(all_checkpoints) > 1 else 'нет'}")
            # Не прерываем, но предупреждение будет видно


print("\n" + "="*60)
print("ОБУЧЕНИЕ ЗАВЕРШЕНО")
print("="*60)

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Tokenizing train dataset:   0%|          | 0/8077 [00:00<?, ? examples/s]

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 1, 'bos_token_id': 2, 'pad_token_id': 0}.

############################################################
# Начинаем обучение: epoch01_easy_ep1of2
# Примеров: 8077, Эпох: 1
# Шагов оптимизатора (приблизительно): 505
############################################################

Обучение завершено. Loss: 1.0734

Лосс эпохи epoch01_easy_ep1of2:
  Нет данных о лоссе.

============================================================
SANITY CHECK после epoch01_easy_ep1of2
============================================================

Prompt : Что такое фотосинтез?
Answer : Фотосинтез — это процесс, в результате которого растения, водоросли и некоторые бактерии преобразуют солнечную энергию в химическую энергию органических соединений с использованием воды и углекислого газа.
model
Фотосинтез — это процесс, в результате которого растения, водоросли и некоторые бактерии
Stats  : 150 токенов, 45 уникальных, pad доля=0.00%

Prompt : Назовите три органоида клетки и их функции.
Answer : Органоиды клетки — это специализированные структуры внутри клетки, выполняющие определённые функции, такие как лизосомы, рибосомы и вакуоли.
model
Лизосомы — это органоиды, содержащие ферменты для расщепления органических веществ; рибосомы — это органоиды, участвующие в синтезе белков; вакуоли — это
Stats  : 150 токенов, 67 уникальных, pad доля=0.00%

Prompt : Почему вода является универсальным растворителем?
Answer : Универсальность воды как растворителя обусловлена её способностью растворять широкий спектр веществ благодаря наличию полярных молекул и способности образовывать водородные связи с различными веществами.
model
Универсальность воды как растворителя обусловлена её способностью растворять широкий спект
Stats  : 150 токенов, 48 уникальных, pad доля=0.00%

✅ Санити-чек пройден после epoch01_easy_ep1of2
  Сохраняем чекпоинт: /content/drive/MyDrive/Colab Notebooks/gemma3_sft/checkpoints/epoch01_easy_ep1of2

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  ✅ Чекпоинт сохранён: /content/drive/MyDrive/Colab Notebooks/gemma3_sft/checkpoints/epoch01_easy_ep1of2

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Tokenizing train dataset:   0%|          | 0/8077 [00:00<?, ? examples/s]

############################################################
# Начинаем обучение: epoch02_easy_ep2of2
# Примеров: 8077, Эпох: 1
# Шагов оптимизатора (приблизительно): 505
############################################################

Обучение завершено. Loss: 0.7613

Лосс эпохи epoch02_easy_ep2of2:
  Нет данных о лоссе.

============================================================
SANITY CHECK после epoch02_easy_ep2of2
============================================================

Prompt : Что такое фотосинтез?
Answer : Фотосинтез — это процесс, в котором растения, водоросли и некоторые бактерии преобразуют солнечную энергию в химическую, создавая органические вещества из воды и углекислого газа
model
Фотосинтез — это процесс, в котором растения, водоросли и некоторые бактерии преобразуют солнечную энергию в химиче
Stats  : 150 токенов, 44 уникальных, pad доля=0.00%

Prompt : Назовите три органоида клетки и их функции.
Answer : Три органоида клетки — это специализированные структуры клетки, выполняющие специфические функции, такие как синтез белков, хранение веществ и участие в клеточном делении.
model
Три органоида клетки — это специализированные структуры клетки, выполняющие специфические функции, такие как синтез белков
Stats  : 150 токенов, 38 уникальных, pad доля=0.00%

Prompt : Почему вода является универсальным растворителем?
Answer : Универсальность воды как растворителя обусловлена её способностью взаимодействовать с широким спектром веществ за счёт наличия полярных молекул и способности образовывать водородные связи.
model
Универсальность воды как растворителя обусловлена её способностью взаимодействовать с широким спектром ве
Stats  : 150 токенов, 47 уникальных, pad доля=0.00%

✅ Санити-чек пройден после epoch02_easy_ep2of2
  Сохраняем чекпоинт: /content/drive/MyDrive/Colab Notebooks/gemma3_sft/checkpoints/epoch02_easy_ep2of2

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  ✅ Чекпоинт сохранён: /content/drive/MyDrive/Colab Notebooks/gemma3_sft/checkpoints/epoch02_easy_ep2of2

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Tokenizing train dataset:   0%|          | 0/12153 [00:00<?, ? examples/s]

############################################################
# Начинаем обучение: epoch03_medium_part1_ep1of1
# Примеров: 12153, Эпох: 1
# Шагов оптимизатора (приблизительно): 760
############################################################

Обучение завершено. Loss: 1.0040

Лосс эпохи epoch03_medium_part1_ep1of1:
  Нет данных о лоссе.

============================================================
SANITY CHECK после epoch03_medium_part1_ep1of1
============================================================

Prompt : Что такое фотосинтез?
Answer : Фотосинтез — это процесс преобразования световой энергии в химическую энергию органических веществ с участием хлорофилла и воды в клетках фотосинтезирующих организмов.
model
Фотосинтез — это процесс, в ходе которого растения, водоросли и некоторые бактерии преобразуют световую энергию в химическую,
Stats  : 150 токенов, 69 уникальных, pad доля=0.00%

Prompt : Назовите три органоида клетки и их функции.
Answer : Ядро — хранение наследственной информации, митохондрии — производство энергии, рибосомы — синтез белков
model
Ядро, митохондрии, рибосомы
model
Ядро — хранение наследственной информации, митохондрии — производство энергии, рибосомы — синтез белков
model
Ядро, митохондрии, рибосомы
model
Ядро, митохо
Stats  : 150 токенов, 28 уникальных, pad доля=0.00%

Prompt : Почему вода является универсальным растворителем?
Answer : Вода является универсальным растворителем, потому что она способна растворять различные вещества, изменяя их физическое состояние и образуя однородную смесь, что позволяет проводить химические реакции в единой фазе.
model
Вода является универсальным растворителем, потому что она способна растворять
Stats  : 150 токенов, 45 уникальных, pad доля=0.00%

✅ Санити-чек пройден после epoch03_medium_part1_ep1of1
  Сохраняем чекпоинт: /content/drive/MyDrive/Colab Notebooks/gemma3_sft/checkpoints/epoch03_medium_part1_ep1of1

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  ✅ Чекпоинт сохранён: /content/drive/MyDrive/Colab Notebooks/gemma3_sft/checkpoints/epoch03_medium_part1_ep1of1

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Tokenizing train dataset:   0%|          | 0/12155 [00:00<?, ? examples/s]

############################################################
# Начинаем обучение: epoch04_medium_part2_ep1of1
# Примеров: 12155, Эпох: 1
# Шагов оптимизатора (приблизительно): 760
############################################################

Обучение завершено. Loss: 0.9476

Лосс эпохи epoch04_medium_part2_ep1of1:
  Нет данных о лоссе.

============================================================
SANITY CHECK после epoch04_medium_part2_ep1of1
============================================================

Prompt : Что такое фотосинтез?
Answer : Фотосинтез — это процесс, в котором растения, водоросли и некоторые бактерии преобразуют световую энергию в химическую, создавая органические вещества из воды и углекислого газа.
model
Фотосинтез — это процесс преобразования световой энергии в химическую, происходящий в хлоропластах растительных кле
Stats  : 150 токенов, 60 уникальных, pad доля=0.00%

Prompt : Назовите три органоида клетки и их функции.
Answer : Цитоплазматическая мембрана, митохондрии, рибосомы
model
Цитоплазматическая мембрана — барьер между клеткой и внешней средой, митохондрии — центры энергетического обмена, рибосомы — центры синтеза белка
model
Цитоплазматическая мембрана, митохондрии, рибосомы
model
Цитоплазматическая мембрана — барь
Stats  : 150 токенов, 44 уникальных, pad доля=0.00%

Prompt : Почему вода является универсальным растворителем?
Answer : Вода является универсальным растворителем, потому что её полярность позволяет ей взаимодействовать с различными веществами, разделяя их молекулы и образуя однородную смесь.
model
Вода является универсальным растворителем, потому что её полярность позволяет ей взаимодействовать с различными веществам
Stats  : 150 токенов, 40 уникальных, pad доля=0.00%

✅ Санити-чек пройден после epoch04_medium_part2_ep1of1
  Сохраняем чекпоинт: /content/drive/MyDrive/Colab Notebooks/gemma3_sft/checkpoints/epoch04_medium_part2_ep1of1

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  ✅ Чекпоинт сохранён: /content/drive/MyDrive/Colab Notebooks/gemma3_sft/checkpoints/epoch04_medium_part2_ep1of1

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Tokenizing train dataset:   0%|          | 0/6479 [00:00<?, ? examples/s]

############################################################
# Начинаем обучение: epoch05_hard_ep1of2
# Примеров: 6479, Эпох: 1
# Шагов оптимизатора (приблизительно): 405
############################################################

Обучение завершено. Loss: 0.9277

Лосс эпохи epoch05_hard_ep1of2:
  Нет данных о лоссе.

============================================================
SANITY CHECK после epoch05_hard_ep1of2
============================================================

Prompt : Что такое фотосинтез?
Answer : Фотосинтез — это процесс преобразования световой энергии в химическую, осуществляемый растениями, водорослями и некоторые бактериями с участием хлорофилла и воды для синтеза органических веществ.
model
Фотосинтез — это процесс преобразования световой энергии в химическую, осуществляемый растениями,
Stats  : 150 токенов, 45 уникальных, pad доля=0.00%

Prompt : Назовите три органоида клетки и их функции.
Answer : Органоиды клетки — это специализированные структуры, выполняющие определённые функции в клетке, такие как синтез белков (рибосомы), хранение веществ (лизосомы) и транспорт веществ (везикулы).
model
Органоиды клетки: рибосомы — синтез белков, лизосомы — расщепление органических веществ, везикулы — тр
Stats  : 150 токенов, 59 уникальных, pad доля=0.00%

Prompt : Почему вода является универсальным растворителем?
Answer : Вода является универсальным растворителем, потому что её полярная молекула способна взаимодействовать с полярными молекулами других веществ, образуя однородную смесь, что позволяет ей растворять широкий спектр соединений.
model
Вода является универсальным растворителем, потому что её полярная молеку
Stats  : 150 токенов, 46 уникальных, pad доля=0.00%

✅ Санити-чек пройден после epoch05_hard_ep1of2
  Сохраняем чекпоинт: /content/drive/MyDrive/Colab Notebooks/gemma3_sft/checkpoints/epoch05_hard_ep1of2

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  ✅ Чекпоинт сохранён: /content/drive/MyDrive/Colab Notebooks/gemma3_sft/checkpoints/epoch05_hard_ep1of2

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Tokenizing train dataset:   0%|          | 0/6479 [00:00<?, ? examples/s]

############################################################
# Начинаем обучение: epoch06_hard_ep2of2
# Примеров: 6479, Эпох: 1
# Шагов оптимизатора (приблизительно): 405
############################################################

Обучение завершено. Loss: 0.7150

Лосс эпохи epoch06_hard_ep2of2:
  Нет данных о лоссе.

============================================================
SANITY CHECK после epoch06_hard_ep2of2
============================================================

Prompt : Что такое фотосинтез?
Answer : Фотосинтез — это процесс преобразования световой энергии в химическую, осуществляемый растениями, водорослями и некоторыми бактериями для синтеза органических веществ из углекислого газа и воды.
model
Фотосинтез — это процесс преобразования световой энергии в химическую, осуществляемый растениями, в
Stats  : 150 токенов, 44 уникальных, pad доля=0.00%

Prompt : Назовите три органоида клетки и их функции.
Answer : Ядро — хранение и передача наследственной информации, митохондрии — производство энергии в виде АТФ, лизосомы — расщепление биополимеров.
model
Ядро, митохондрии, лизосомы
model
Ядро — хранение и передача наследственной информации, митохондрии — производство энергии в виде АТФ, лизосомы — расщеплени
Stats  : 150 токенов, 40 уникальных, pad доля=0.00%

Prompt : Почему вода является универсальным растворителем?
Answer : Вода является универсальным растворителем, потому что её полярная структура позволяет ей взаимодействовать с различными веществами, образуя однородные смеси, что делает её способной растворять широкий спектр соединений.
model
Вода является универсальным растворителем, потому что её полярная структур
Stats  : 150 токенов, 45 уникальных, pad доля=0.00%

✅ Санити-чек пройден после epoch06_hard_ep2of2
  Сохраняем чекпоинт: /content/drive/MyDrive/Colab Notebooks/gemma3_sft/checkpoints/epoch06_hard_ep2of2

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  ✅ Чекпоинт сохранён: /content/drive/MyDrive/Colab Notebooks/gemma3_sft/checkpoints/epoch06_hard_ep2of2

============================================================
ОБУЧЕНИЕ ЗАВЕРШЕНО
============================================================